gf_urban: 0.55e-4
gf_smoke: 4e-4
gf_dust: 0.3e-4
delta_urban: 0.05
delta_smoke: 0.06
delta_dust: 0.26
variation_coefficient: 0.1
input_dir: "./"
num_points: 100
do_smooth: true
sigma_h: 5
sigma_t: 3
size: 7
avg_percent: 0.1
